
export const bgColor = "bg-orange-500";

export const wordPools = {
  easy: [
    "apple",
    "beach",
    "chair",
    "dance",
    "eagle",
    "flame",
    "grape",
    "heart",
    "image",
    "juice",
    "kite",
    "lemon",
    "music",
    "north",
    "ocean",
    "paint",
    "queen",
    "river",
    "smile",
    "table",
    "uncle",
    "voice",
    "water",
    "youth",
    "zebra",
    "bread",
    "cloud",
    "dream",
    "flash",
    "green",
    "honey",
    "ivory",
    "jumbo",
    "knife",
    "light",
    "money",
    "nurse",
    "paper",
    "quiet",
    "radio",
    "snake",
    "tiger",
    "umbrella",
    "video",
    "whale",
    "amber",
    "brick",
    "candy",
    "daisy",
    "earth",
    "fairy",
    "glass",
    "happy",
    "index",
    "jelly",
    "lunar",
    "magic",
    "noble",
    "olive",
    "pearl",
    "quilt",
    "royal",
    "sugar",
    "tulip",
    "urban",
    "vault",
    "wagon",
    "xenon",
    "yacht",
    "zesty",
  ],
  medium: [
    "balloon",
    "captain",
    "diamond",
    "elephant",
    "factory",
    "garden",
    "harmony",
    "island",
    "journey",
    "kitchen",
    "library",
    "machine",
    "network",
    "octopus",
    "penguin",
    "quality",
    "rainbow",
    "science",
    "thunder",
    "uniform",
    "village",
    "warrior",
    "crystal",
    "dolphin",
    "eclipse",
    "falcon",
    "glacier",
    "horizon",
    "ignite",
    "jasmine",
    "kangaroo",
    "leopard",
    "mineral",
    "neutron",
    "orchids",
    "phoenix",
    "quantum",
    "raccoon",
    "sapphire",
    "tornado",
    "unicorn",
    "volcano",
    "walrus",
    "xylophone",
    "yogurt",
    "zephyr",
    "bamboo",
    "cascade",
    "dazzle",
    "emerald",
    "flamingo",
    "gazelle",
    "harvest",
    "impulse",
    "jaguar",
    "koala",
    "lantern",
    "mammoth",
    "nebula",
    "ocelot",
    "panther",
    "quasar",
    "reptile",
    "scarlet",
    "textile",
    "upgrade",
    "velvet",
    "whisper",
    "yonder",
    "zenith",
  ],
  hard: [
    "adventure",
    "beautiful",
    "challenge",
    "discovery",
    "education",
    "fountain",
    "grateful",
    "heritage",
    "industry",
    "junction",
    "knowledge",
    "language",
    "mountain",
    "navigate",
    "obstacle",
    "paradise",
    "question",
    "resource",
    "schedule",
    "treasure",
    "universe",
    "valuable",
    "warranty",
    "abstract",
    "backbone",
    "calendar",
    "database",
    "elephant",
    "festival",
    "geometry",
    "harmonic",
    "infinite",
    "judgment",
    "keyboard",
    "leverage",
    "magnetic",
    "nitrogen",
    "operator",
    "platinum",
    "quadrant",
    "relative",
    "sequence",
    "terminal",
    "ultimate",
    "vacation",
    "wavelength",
    "yearbook",
    "zoology",
    "academic",
    "baseline",
    "capacity",
    "deadline",
    "engineer",
    "feedback",
    "graphics",
    "hardware",
    "imperial",
    "junction",
    "kinetics",
    "leverage",
    "molecule",
    "notebook",
    "optimize",
    "protocol",
    "quantity",
    "research",
    "software",
    "template",
    "upgrade",
    "validate",
    "wireless",
    "accelerate",
    "benchmark",
    "calculate",
    "dashboard",
    "elaborate",
    "framework",
    "generate",
    "highlight",
    "implement",
    "junction",
    "keyboard",
    "landscape",
    "mechanism",
    "normalize",
    "optimize",
    "parameter",
    "qualified",
    "reference",
    "structure",
    "technical",
    "underline",
    "validate",
    "workshop",
    "architect",
    "blueprint",
    "component",
    "developer",
    "ecosystem",
    "frequency",
    "generator",
    "hierarchy",
    "interface",
    "knowledge",
  ],
};

export const getGameSettings = (level: number) => {
  return {
    correctStreakLimit: 3,
    wrongStreakLimit: 2,
    basePoints: 1, // Single base point value
    levelMultiplier: level,
    maxLevel: 6,
    minLevel: 1,
  };
};

// Get random word based on level
export const getRandomWord = (level: number) => {
  let pool;
  if (level <= 2) pool = wordPools.easy;
  else if (level <= 4) pool = wordPools.medium;
  else pool = wordPools.hard;

  return pool[Math.floor(Math.random() * pool.length)];
};

// Scramble the word
export const scrambleWord = (word: string) => {
    const arr = word.split("");
    for (let i = arr.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [arr[i], arr[j]] = [arr[j], arr[i]];
    }
    return arr.join("");
  };