const trueFalseDataset = [
  { statement: "The sun rises in the east.", answer: true },
  { statement: "Humans have three lungs.", answer: false },
  { statement: "A year has 365 days.", answer: true },
  { statement: "Water boils at 100 degrees Celsius.", answer: true },
  { statement: "Venus is the closest planet to the sun.", answer: false },
  { statement: "Mount Everest is the highest mountain on Earth.", answer: true },
  { statement: "Birds are mammals.", answer: false },
  { statement: "An octopus has three hearts.", answer: true },
  { statement: "Bananas grow on trees.", answer: false }, // They grow on plants.
  { statement: "Sharks are fish.", answer: true },
  { statement: "Pluto is still considered a planet.", answer: false },
  { statement: "The Eiffel Tower is in Berlin.", answer: false },
  { statement: "Photosynthesis occurs in plants.", answer: true },
  { statement: "Electricity is a primary energy source.", answer: false },
  { statement: "The human skeleton has over 200 bones.", answer: true },
  { statement: "Jupiter has more moons than Mars.", answer: true },
  { statement: "Australia is the largest continent.", answer: false },
  { statement: "Cats are herbivores.", answer: false },
  { statement: "A liter of water weighs 1 kilogram.", answer: true },
  { statement: "Sound travels faster in water than in air.", answer: true },
  { statement: "The human brain is made up of 60% fat.", answer: true },
  { statement: "Camels have one hump.", answer: false }, // Some have two humps.
  { statement: "Fish breathe through their gills.", answer: true },
  { statement: "Lightning never strikes the same place twice.", answer: false },
  { statement: "Honey never spoils.", answer: true },
  { statement: "The largest mammal is the blue whale.", answer: true },
  { statement: "Dolphins are a type of fish.", answer: false },
  { statement: "Mitochondria are found in plant cells.", answer: true },
  { statement: "Bats are blind.", answer: false },
    { statement: "The Atlantic is the largest ocean on Earth.", answer: false },
];
